version: "2.1"

services:

  app-postgres:
    image: postgres:11-alpine
    container_name: app-postgres
    restart: always
    environment:
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
         - ./postgres/data:/var/lib/postgresql/data
    networks:
      app-test-net:
        aliases:
          - app-postgres

  app-test:
    container_name: app-test
    build: python-sample-app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - app-postgres
    networks:
      app-test-net:
        aliases:
          - app-test

networks:
  app-test-net:
    external: false
