version: "3.5"

services:

  app-postgres:
    image: postgres:11-alpine
    container_name: app-postgres
#    deploy:
#      replicas: 1
    restart: always
    environment:
#      POSTGRES_USER: worker
#      POSTGRES_DB: app
#      POSTGRES_PASSWORD: worker
#      PGDATA: /postgres
    environment:
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
      - POSTGRES_DB=app

    ports:
      - 5432:5432
    volumes:
         - ./postgres/data:/var/lib/postgresql/data
#      - type: bind
#         source: /opt/sier/keys
#         target:/var/opt/cprocsp/keys/root
    networks:
      app-test-net:
        aliases:
          - app-postgres



networks:
  app-test-net:
    external: false
