version: "2.3"

services:

  app-postgres:
    image: postgres:11-alpine
    container_name: app-postgres
#    deploy:
#      replicas: 1
    restart: always
    environment:
      POSTGRES_PASSWORD: worker
#      POSTGRES_USER: worker
#      POSTGRES_DB: app
    ports:
      - 5432:5432
#    volumes:
#      - type: bind
#         source: /opt/sier/templates
#         target:/opt/templates
#      - type: bind
#         source: /opt/sier/keys
#         target:/var/opt/cprocsp/keys/root
    networks:
      app-test-net:
        aliases:
          - app-postgres



networks:
  app-test-net:
    driver: bridge
